on:
  workflow_dispatch:
  push:
    tags: ['*']

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://npm.pkg.github.com/
        scope: '@staff0rd'
    - name: npm install
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: npm build
      run: npm run build
    - name: npm test
      run: npm run test
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - uses: jakejarvis/s3-sync-action@master
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: atqu.in
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'build'
        DEST_DIR: 'games/dev/garage/v${{ steps.package-version.outputs.current-version }}'
